/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LabRouteImport } from './routes/lab'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as InfraRouteImport } from './routes/infra'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AiBrainRouteImport } from './routes/ai-brain'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatBackup1779147851RouteImport } from './routes/chat.backup.1779147851'
import { Route as ApiChatLovableBackupRouteImport } from './routes/api/chat.lovable.backup'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraRoute = InfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBrainRoute = AiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBackup1779147851Route = ChatBackup1779147851RouteImport.update({
  id: '/backup/1779147851',
  path: '/backup/1779147851',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatLovableBackupRoute = ApiChatLovableBackupRouteImport.update({
  id: '/chat/lovable/backup',
  path: '/chat/lovable/backup',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-brain': typeof AiBrainRoute
  '/api': typeof ApiRouteWithChildren
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRouteWithChildren
  '/infra': typeof InfraRoute
  '/investigate': typeof InvestigateRoute
  '/lab': typeof LabRoute
  '/learning': typeof LearningRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategy': typeof StrategyRoute
  '/tasks': typeof TasksRoute
  '/trading': typeof TradingRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/workspace': typeof WorkspaceRoute
  '/chat/backup/1779147851': typeof ChatBackup1779147851Route
  '/api/chat/lovable/backup': typeof ApiChatLovableBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-brain': typeof AiBrainRoute
  '/api': typeof ApiRouteWithChildren
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRouteWithChildren
  '/infra': typeof InfraRoute
  '/investigate': typeof InvestigateRoute
  '/lab': typeof LabRoute
  '/learning': typeof LearningRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategy': typeof StrategyRoute
  '/tasks': typeof TasksRoute
  '/trading': typeof TradingRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/workspace': typeof WorkspaceRoute
  '/chat/backup/1779147851': typeof ChatBackup1779147851Route
  '/api/chat/lovable/backup': typeof ApiChatLovableBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-brain': typeof AiBrainRoute
  '/api': typeof ApiRouteWithChildren
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRouteWithChildren
  '/infra': typeof InfraRoute
  '/investigate': typeof InvestigateRoute
  '/lab': typeof LabRoute
  '/learning': typeof LearningRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/strategy': typeof StrategyRoute
  '/tasks': typeof TasksRoute
  '/trading': typeof TradingRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/workspace': typeof WorkspaceRoute
  '/chat/backup/1779147851': typeof ChatBackup1779147851Route
  '/api/chat/lovable/backup': typeof ApiChatLovableBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/ai-brain'
    | '/api'
    | '/automation'
    | '/chat'
    | '/infra'
    | '/investigate'
    | '/lab'
    | '/learning'
    | '/logs'
    | '/memory'
    | '/models'
    | '/research'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/signals'
    | '/strategy'
    | '/tasks'
    | '/trading'
    | '/vault'
    | '/voice'
    | '/workspace'
    | '/chat/backup/1779147851'
    | '/api/chat/lovable/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/ai-brain'
    | '/api'
    | '/automation'
    | '/chat'
    | '/infra'
    | '/investigate'
    | '/lab'
    | '/learning'
    | '/logs'
    | '/memory'
    | '/models'
    | '/research'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/signals'
    | '/strategy'
    | '/tasks'
    | '/trading'
    | '/vault'
    | '/voice'
    | '/workspace'
    | '/chat/backup/1779147851'
    | '/api/chat/lovable/backup'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/ai-brain'
    | '/api'
    | '/automation'
    | '/chat'
    | '/infra'
    | '/investigate'
    | '/lab'
    | '/learning'
    | '/logs'
    | '/memory'
    | '/models'
    | '/research'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/signals'
    | '/strategy'
    | '/tasks'
    | '/trading'
    | '/vault'
    | '/voice'
    | '/workspace'
    | '/chat/backup/1779147851'
    | '/api/chat/lovable/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AiBrainRoute: typeof AiBrainRoute
  ApiRoute: typeof ApiRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  ChatRoute: typeof ChatRouteWithChildren
  InfraRoute: typeof InfraRoute
  InvestigateRoute: typeof InvestigateRoute
  LabRoute: typeof LabRoute
  LearningRoute: typeof LearningRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  ResearchRoute: typeof ResearchRoute
  ScannerRoute: typeof ScannerRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  StrategyRoute: typeof StrategyRoute
  TasksRoute: typeof TasksRoute
  TradingRoute: typeof TradingRoute
  VaultRoute: typeof VaultRoute
  VoiceRoute: typeof VoiceRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra': {
      id: '/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof InfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-brain': {
      id: '/ai-brain'
      path: '/ai-brain'
      fullPath: '/ai-brain'
      preLoaderRoute: typeof AiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/backup/1779147851': {
      id: '/chat/backup/1779147851'
      path: '/backup/1779147851'
      fullPath: '/chat/backup/1779147851'
      preLoaderRoute: typeof ChatBackup1779147851RouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat/lovable/backup': {
      id: '/api/chat/lovable/backup'
      path: '/chat/lovable/backup'
      fullPath: '/api/chat/lovable/backup'
      preLoaderRoute: typeof ApiChatLovableBackupRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiChatLovableBackupRoute: typeof ApiChatLovableBackupRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiChatLovableBackupRoute: ApiChatLovableBackupRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface ChatRouteChildren {
  ChatBackup1779147851Route: typeof ChatBackup1779147851Route
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatBackup1779147851Route: ChatBackup1779147851Route,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AiBrainRoute: AiBrainRoute,
  ApiRoute: ApiRouteWithChildren,
  AutomationRoute: AutomationRoute,
  ChatRoute: ChatRouteWithChildren,
  InfraRoute: InfraRoute,
  InvestigateRoute: InvestigateRoute,
  LabRoute: LabRoute,
  LearningRoute: LearningRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  ResearchRoute: ResearchRoute,
  ScannerRoute: ScannerRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  StrategyRoute: StrategyRoute,
  TasksRoute: TasksRoute,
  TradingRoute: TradingRoute,
  VaultRoute: VaultRoute,
  VoiceRoute: VoiceRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
